[build]
  command = "echo 'Il sito Ã¨ pronto!'"
  publish = "."

[[redirects]]
  from = "/PDF/*"
  to = "/PDF/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }
