[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/PDF/**"
  to = "/PDF/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/public/.well-known/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }
